# Copyright 2023 The Nephio Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: networkfunction.nephio.io/v1alpha1
kind: NfResource
metadata:
  name: free5gc-upf-1
  namespace: default
spec:
  namespace: upf-1
  clustername: nephio-edge-1
  upfnad:
    n3cni: macvlan
    n3master: ens4
    n3gw: 10.10.5.1
    n4cni: macvlan
    n4master: ens4
    n4gw: 192.168.100.1
    n6cni: macvlan
    n6master: ens4
    n6gw: 10.20.3.1
