apiVersion: networkfunction.nephio.io/v1alpha1
kind: NfResource
metadata:
  name: free5gc-upf-1
  namespace: default
spec:
  namespace: upf-1
  clustername: nephio-edge-1
  upfnad:
    n3cni: macvlan
    n3master: ens4
    n3gw: 10.10.5.1
    n4cni: macvlan
    n4master: ens4
    n4gw: 192.168.100.1
    n6cni: macvlan
    n6master: ens4
    n6gw: 10.20.3.1
